// Generated by analyze.py
#ifndef LIMITS_CPP
#define LIMITS_CPP

#include <array>
#include "types.cpp"

#if TESTCASE == 1
constexpr const int N = 7;
constexpr const int W = 100;
constexpr const int H = 100;
#elif TESTCASE == 2
constexpr const int N = 22;
constexpr const int W = 200;
constexpr const int H = 100;
#elif TESTCASE == 3
constexpr const int N = 1000;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 4
constexpr const int N = 1000;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 5
constexpr const int N = 1000;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 6
constexpr const int N = 1000;
constexpr const int W = 2000;
constexpr const int H = 777;
#elif TESTCASE == 7
constexpr const int N = 420;
constexpr const int W = 2000;
constexpr const int H = 200;
#elif TESTCASE == 8
constexpr const int N = 656;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 9
constexpr const int N = 746;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 10
constexpr const int N = 900;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 11
constexpr const int N = 900;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 12
constexpr const int N = 157;
constexpr const int W = 1123;
constexpr const int H = 1123;
#elif TESTCASE == 13
constexpr const int N = 157;
constexpr const int W = 1123;
constexpr const int H = 1123;
#elif TESTCASE == 14
constexpr const int N = 1000;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 15
constexpr const int N = 1000;
constexpr const int W = 2048;
constexpr const int H = 640;
#elif TESTCASE == 16
constexpr const int N = 1000;
constexpr const int W = 640;
constexpr const int H = 2048;
#elif TESTCASE == 17
constexpr const int N = 2183;
constexpr const int W = 1503;
constexpr const int H = 1462;
#elif TESTCASE == 18
constexpr const int N = 2189;
constexpr const int W = 1940;
constexpr const int H = 320;
#elif TESTCASE == 19
constexpr const int N = 2858;
constexpr const int W = 860;
constexpr const int H = 860;
#elif TESTCASE == 20
constexpr const int N = 2600;
constexpr const int W = 1121;
constexpr const int H = 1539;
#elif TESTCASE == 21
constexpr const int N = 2730;
constexpr const int W = 1001;
constexpr const int H = 1023;
#elif TESTCASE == 22
constexpr const int N = 353;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 23
constexpr const int N = 561;
constexpr const int W = 555;
constexpr const int H = 2222;
#elif TESTCASE == 24
constexpr const int N = 276;
constexpr const int W = 2222;
constexpr const int H = 777;
#elif TESTCASE == 25
constexpr const int N = 235;
constexpr const int W = 777;
constexpr const int H = 777;
#elif TESTCASE == 26
constexpr const int N = 7;
constexpr const int W = 100;
constexpr const int H = 100;
#elif TESTCASE == 27
constexpr const int N = 22;
constexpr const int W = 200;
constexpr const int H = 100;
#elif TESTCASE == 28
constexpr const int N = 1000;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 29
constexpr const int N = 1001;
constexpr const int W = 1023;
constexpr const int H = 1023;
#elif TESTCASE == 30
constexpr const int N = 1000;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 31
constexpr const int N = 987;
constexpr const int W = 911;
constexpr const int H = 911;
#elif TESTCASE == 32
constexpr const int N = 507;
constexpr const int W = 1500;
constexpr const int H = 1500;
#elif TESTCASE == 33
constexpr const int N = 517;
constexpr const int W = 1414;
constexpr const int H = 1414;
#elif TESTCASE == 34
constexpr const int N = 900;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 35
constexpr const int N = 888;
constexpr const int W = 1111;
constexpr const int H = 1111;
#elif TESTCASE == 36
constexpr const int N = 892;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 37
constexpr const int N = 1029;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 38
constexpr const int N = 1027;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 39
constexpr const int N = 1027;
constexpr const int W = 500;
constexpr const int H = 2000;
#elif TESTCASE == 40
constexpr const int N = 1027;
constexpr const int W = 2000;
constexpr const int H = 500;
#elif TESTCASE == 41
constexpr const int N = 157;
constexpr const int W = 1123;
constexpr const int H = 1123;
#elif TESTCASE == 42
constexpr const int N = 157;
constexpr const int W = 1123;
constexpr const int H = 1123;
#elif TESTCASE == 43
constexpr const int N = 1027;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 44
constexpr const int N = 1027;
constexpr const int W = 500;
constexpr const int H = 2000;
#elif TESTCASE == 45
constexpr const int N = 1027;
constexpr const int W = 2000;
constexpr const int H = 500;
#elif TESTCASE == 46
constexpr const int N = 321;
constexpr const int W = 1000;
constexpr const int H = 1000;
#elif TESTCASE == 47
constexpr const int N = 570;
constexpr const int W = 555;
constexpr const int H = 2222;
#elif TESTCASE == 48
constexpr const int N = 280;
constexpr const int W = 2222;
constexpr const int H = 777;
#elif TESTCASE == 49
constexpr const int N = 234;
constexpr const int W = 777;
constexpr const int H = 777;
#elif TESTCASE == 50
constexpr const int N = 245;
constexpr const int W = 3000;
constexpr const int H = 500;
#else
constexpr const int N = 2858;
constexpr const int W = 3000;
constexpr const int H = 2222;
#endif // TESTCASE
#endif // LIMITS_CPP